name: AUTO KOMA TRADE

on:
  schedule:
    - cron: '*/2 * * * *'
  workflow_dispatch:

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install ccxt pandas requests
      - run: python main.py
        env:
          MEXC_API_KEY: ${{ secrets.MEXC_API_KEY }}
          MEXC_API_SECRET: ${{ secrets.MEXC_API_SECRET }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          AUTOPILOT_ENABLED: "true"
          ENGINE: "BOTH"
