name: cleanup
on: workflow_dispatch
jobs:
  clean:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const runs = await github.paginate(github.rest.actions.listWorkflowRunsForRepo, { owner: context.repo.owner, repo: context.repo.repo, per_page: 100 });
            console.log(`Found ${runs.length} runs`);
            for (const r of runs.slice(150)) {
              console.log(`Deleting ${r.id}`);
              await github.rest.actions.deleteWorkflowRun({ owner: context.repo.owner, repo: context.repo.repo, run_id: r.id });
            }
